[package]
name = "recipe_parser"
version = "0.1.0"
edition = "2021"
description = "A parser for food recipes. Divides recipes into: name, description, ingredients and instructions."

[dependencies]
anyhow = "1.0.91"
pest = "2.7.14"
pest_derive = "2.7.14"
